# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0004_grade_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='bill',
            field=models.IntegerField(default=1000),
        ),
    ]
