# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Two', '0006_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('is_delete', models.BooleanField(default=False)),
            ],
        ),
    ]
