# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-26 08:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'ChinaPeople'},
        ),
    ]
