# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20190826_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='p_hobby',
            field=models.CharField(db_column='hobby', max_length=32, null=True),
        ),
    ]
